jarwer_user:
    resource: "@JarwerUserBundle/Controller/"
    type:     annotation
    prefix:   /

a_en_red_gamification:
    resource: "@AEnRedGamificationBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
